### ISSUE TITLE
Docker support

### ISSUE THREAD

**Issue by mariushosting** [btahir/next-beats#1]
Awesome wonderful project! Please add a docker image.

**Comment by btahir** [comment]
Thanks. Added.

**Comment by mariushosting** [comment]
> Thanks. Added.

Can you please upload the image and maintain it on Github or Docker hub?

**Comment by btahir** [comment]
I'm not entirely sure that this approach would be useful to most people, but if you think it could help, feel free to go ahead and implement it!
